### ISSUE TITLE
malformed ciconums for 5 marc records

### ISSUE THREAD

**Issue by cwulfman** [pulibrary/cicognara-catalogo#15] opened 2016-04-22 15:52 UTC
The value in 024$a is a quoted 8-digit string; looks like it is supposed to be two separate cico numbers:

Voyager ids (control field 001):

1. 8542302 (" 37213724")
2. 8546181 ("39644134")
3. 8546310 ("39854168")
4. 8544316 ("39974003")
5. 8542571 (" 40254716")

**Comment by cwulfman** [comment] 2016-04-26 22:27
In order to collate the digital cico ids in the TEI source file, I made the following edits to cicognara.mrx.xml. This ticket should **not** be closed until Tech Svcs edits the original records.

    8542302 (" 37213724")  ---> 3721
    8546181 ("39644134")   ---> 3964
    8546310 ("39854168")   ---> 3985
    8544316 ("39974003")   ---> 3997
    8542571 (" 40254716")  ---> 4025

**Comment by jpstroop** [comment] 2016-04-27 00:25
@cwulfman, what are the numbers in parentheses? (Also, you can tag @joycebcat on github).

**Comment by jpstroop** [comment] 2016-04-27 00:27
Oh. @jpstroop reads the issue. I get it now. :wink:

**Comment by joycebcat** [comment] 2016-04-27 14:30
@cwulfman Hi Cliff, yes, you can tag me in github.  I'm not clear whether something is expected of me here, and if so, what exactly that is.  Help?

**Comment by jpstroop** [comment] 2016-04-27 14:34
@joycebcat See the original issue. @cwulfman uncovered some digital cico. numbers that were concatenated in the MARC records. Not clear to me if they should be split into two separate `024` fields, or truncated as he has done in our copy.

**Comment by jpstroop** [comment] 2016-04-27 14:44
Sorry, they're catalog numbers, not digital

**Comment by cwulfman** [comment] 2016-04-27 20:30
I suspect they should be split into two separate `024` fields, but I thought you @joycebcat , would want to verify that the two split numbers really refer to the right things -- and in any case, I'm just working from Jon's derivative file, so whatever changes I'm making are "local".

**Comment by joycebcat** [comment] 2016-04-28 13:54
@cwulfman All of these except the first one appear to be duplicate entries in the Catalogo, so I have created separate 024 fields in the MARC records, one for each of the two numbers which were originally concatenated.  The only one with a single number is this one:
8542302 (" 37213724")  ---> 3721

This ticket can be closed.

**Comment by cwulfman** [comment] 2016-04-28 14:30
I will update the catalogo transcription to include both embedded cico numbers and then close the ticket.

**Comment by jpstroop** [comment] 2016-04-28 19:43
To answer the question that diappeared: Generally there's a pull request associated with an issue, and when that PT is merged, the issue is close the the message in the PR that say "Closes #x", "Fixes #y" etc. Alternatively, some tickets are deemed irrelevant or redundant, and they're usually closed by whomever.

**Closed** 2016-06-28 19:05 UTC
Labels: numbering error
